spring:
  data:
    mongodb:
      uri: mongodb+srv://root:root@sandbox.daqr5.mongodb.net/products-inventory-database?retryWrites=true&w=majority&appName=Sandbox
  application:
    name: product-service

server:
  port: 8070